= Project Charter - Rocketman
Hain Lukas, Plkolb Marcel, Kaufmann Jan
1.0.0, 2020-10-06
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Project Charter

=== Project Name
Rocketman

=== Project Initiator
There has to be an easy way to transfer data from the rocket to the control unit (probably LoRa-modules).

=== Task definition
With the mobile control unit it should be possible to ignite model rockets by cable and to communicate wirelessly (control and reception of telemetry data) with several outposts simultaneously. The communication should take place in two frequency ranges or with two protocols at the same time (433 MHz LoRa and 802.11b/g/n network via XBee 568).

==== Project main tasks
The mobile control unit has to have a high radio transmission range to be able to receive telemetry data even when the rocket is at a high altitude, presumably 500 meters (Source: CanSat website). It also has to be possible to receive up to 4 video streams simultaneously from the rocket. Further it has to be possible to generate an impulse of at least 12V@2A to launch the rocket, this launch has to be able to be aborted at any time with a separate button. Further more it has to be able to run on an independent power source which has to handle all functions without issues.

=== Project goal
It is easily possible to send telemetry data to the mobile control unit to participate at the CanSat Competition. The participants are able to steer the rocket and the CanSat. It is now also possible to receive video streams from the rocket and CanSat.

=== Project phases

|===
|Phase |Start date |End date

|Documentation
|28.08.2020
|Ongoing
|===

=== Project start/end
The project started on 28. September 2020 with the project proposal. +
It should be finished by the end of this school year.

=== Project resources
See *Rocketman_Partslist.pdf*

=== Project risk
A failure in the launch electronics could destroy the mobile control unit and/or the rocket. Wrong configuration of the LoRa or xBee modules could lead to the disqualification from the CanSat competition.

=== Project team
|===
|Name |Class

|Hain Lukas
|4AHIF

|Plakolb Marcel
|4AHIF

|Kaufmann Jan
|4AHIF

|Dumfarth Felix
|4AHITM

|Feichtinger Sarah
|4AHITM
|===


